name: Deploy to Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

env:
  DOCKER_IMAGE_NAME: java-hello-world
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENVIRONMENT: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set image tag
      id: image
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
        
    - name: Configure kubectl for Staging
      run: |
        mkdir -p ~/.kube
        printf '%s\n' "${{ secrets.KUBE_CONFIG_STAGING }}" > ~/.kube/config
        chmod 600 ~/.kube/config
        
    - name: Prepare Kubernetes manifests
      run: |
        # Create staging-specific manifests
        cp -r k8s k8s-staging
        
        # Update namespace for staging
        sed -i 's/name: java-hello-world/name: java-hello-world-staging/g' k8s-staging/*.yaml
        sed -i 's/namespace: java-hello-world/namespace: java-hello-world-staging/g' k8s-staging/*.yaml
        
        # Update image reference
        sed -i "s|IMAGE_PLACEHOLDER|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image.outputs.tag }}|g" k8s-staging/deployment.yaml
        
        # Add staging-specific labels and annotations
        sed -i '/metadata:/a\  labels:\n    environment: staging' k8s-staging/*.yaml
        
        # Increase replicas for staging
        sed -i 's/replicas: 1/replicas: 2/g' k8s-staging/deployment.yaml
        
    - name: Deploy to Staging AKS
      run: |
        echo "Deploying to Staging environment..."
        kubectl apply -f k8s-staging/namespace.yaml
        kubectl apply -f k8s-staging/deployment.yaml
        kubectl apply -f k8s-staging/service.yaml
        kubectl apply -f k8s-staging/ingress.yaml
        
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=available --timeout=300s deployment/java-hello-world -n java-hello-world-staging
        
    - name: Get deployment status
      run: |
        echo "=== Pods ===" 
        kubectl get pods -n java-hello-world-staging
        echo "=== Services ===" 
        kubectl get services -n java-hello-world-staging
        echo "=== Ingress ===" 
        kubectl get ingress -n java-hello-world-staging
        
    - name: Run comprehensive tests
      run: |
        echo "Running comprehensive tests against staging environment..."
        
        # Get the service endpoint
        EXTERNAL_IP=$(kubectl get service java-hello-world -n java-hello-world-staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || echo "")
        
        if [[ -z "$EXTERNAL_IP" ]]; then
          echo "Using port-forward for testing..."
          kubectl port-forward service/java-hello-world 8080:8080 -n java-hello-world-staging &
          PORT_FORWARD_PID=$!
          sleep 10
          ENDPOINT="http://localhost:8080"
        else
          echo "Testing external endpoint: $EXTERNAL_IP"
          ENDPOINT="http://$EXTERNAL_IP:8080"
        fi
        
        # Health check
        if curl -f $ENDPOINT --max-time 10; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed"
          exit 1
        fi
        
        # Load test (basic)
        echo "Running basic load test..."
        for i in {1..10}; do
          if ! curl -f $ENDPOINT --max-time 5; then
            echo "❌ Load test failed on request $i"
            exit 1
          fi
        done
        echo "✅ Load test passed"
        
        # Performance test
        echo "Running performance test..."
        RESPONSE_TIME=$(curl -o /dev/null -s -w '%{time_total}' $ENDPOINT)
        if (( $(echo "$RESPONSE_TIME < 2.0" | bc -l) )); then
          echo "✅ Performance test passed (${RESPONSE_TIME}s)"
        else
          echo "⚠️ Performance test warning - response time: ${RESPONSE_TIME}s"
        fi
        
        [[ -n "$PORT_FORWARD_PID" ]] && kill $PORT_FORWARD_PID 2>/dev/null || true
        
    - name: Deployment summary
      run: |
        echo "## Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "✅ Deployed to Staging AKS cluster" >> $GITHUB_STEP_SUMMARY
        echo "✅ Health checks passed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Load tests passed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Performance tests completed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** Staging" >> $GITHUB_STEP_SUMMARY
        echo "**Namespace:** \`java-hello-world-staging\`" >> $GITHUB_STEP_SUMMARY
        echo "**Replicas:** 2" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
        
    - name: Notify Slack on successful deployment
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: |
          ✅ Staging deployment completed successfully!
          
          Repository: ${{ github.repository }}
          Environment: Staging
          Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image.outputs.tag }}
          Namespace: java-hello-world-staging
          
          Ready for UAT and production promotion!
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}